### ISSUE TITLE
Allow user to provide system installed libraries

### ISSUE THREAD

**Issue by chivakker** [google/rtc-video-quality#6]
This could help with debugging.  For example, I want to have my own compiled version of libvpx, libyami and  company on a dedicated folder in my path.  I don't want to run the setup* scripts but use that instead.  

As a result, rtc-video-quality should report when an option on the libraries is not supported.

**Comment by pbos** [comment]
I assume vpxdec and ./setup.sh as a dependency is fine but that $PATH is used for encoders. This uses libvpx/tiny_ssim binaries that are not part of any standard distro as far as I'm aware.

What do you mean "when an option on the libraries is not supported"? Is this part what I just filed as #7? E.g. if you tell it to use libvpx, and look in $PATH for binaries, and vpxenc is not in PATH, it'll fail?
