### ISSUE TITLE
libvpx vp9enc rt encoding is way off the target bitrate due to cpu-used option

### ISSUE THREAD

**Issue by chivakker** [google/rtc-video-quality#9]
using rtc-video-quality for vp9enc will set --cpu-used=7.  When setting the target bitrate to 400Kbps this is the result

{ 'actual-bitrate-bps': 547721.7882352942,
  'actual-encode-time-ms': 77934.56983566284,
  'avg-psnr': 35.749396,
  'avg-psnr-u': 41.3453,
  'avg-psnr-v': 41.440348,
  'avg-psnr-y': 34.403333,
  'bitrate-config-kbps': [400],
  'bitrate-utilization': 1.3693044705882353,
  'codec': 'vp9',
  'encode-time-utilization': 2.750631876552806,
  'encoder': 'libvpx-rt',
  'fps': 30.0,
  'frame-bytes': [ 16980,
                   2780,
                   2634,
                   2368,
                   2551,
                   3169,

whle with yami the result is

[{ 'actual-bitrate-bps': 418750.87058823527,
  'actual-encode-time-ms': 4427.440881729126,
  'avg-psnr': 33.7104,
  'avg-psnr-u': 39.335324,
  'avg-psnr-v': 39.315309,
  'avg-psnr-y': 32.367415,
  'bitrate-config-kbps': [400],
  'bitrate-utilization': 1.0468771764705882,
  'codec': 'vp9',
  'encode-time-utilization': 0.15626261935514563,
  'encoder': 'yami',
  'fps': 30.0,
  'frame-bytes': [ 14768,
                   303,
                   320,
                   383,
                   491,

By picking --cpu-used=4 is a good compromise.  This was run on a Yoga 910 with Fedora 25

{ 'actual-bitrate-bps': 414493.55294117646,
  'actual-encode-time-ms': 326446.2540149689,
  'avg-psnr': 34.466931,
  'avg-psnr-u': 39.994153,
  'avg-psnr-v': 40.389453,
  'avg-psnr-y': 33.112922,
  'bitrate-config-kbps': [400],
  'bitrate-utilization': 1.0362338823529411,
  'codec': 'vp9',
  'encode-time-utilization': 11.52163249464596,
  'encoder': 'libvpx-rt',
  'fps': 30.0,
  'frame-bytes': [ 11657,
                   1465,
                   1030,
                   860,
                   850,
                   954,
                   905,

**Comment by pbos** [comment]
Which clip did you use for this run?

**Comment by pbos** [comment]
I'm disinclined to change the settings from what WebRTC uses. We can configure libvpx to use more CPU, but it'll be really unfair to yamiencode. If you up the QP max we'll probably be closer to apples-to-apples but here webrtc will overshoot and drop frames, which is correctly represented by the data point overshooting.
